In [2]:
#Import
import os

#Import other stuff
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
from flask import Flask, render_template, request
#Caching imports
from flask_caching import Cache
import io

In [29]:
	#Scrape standings from basketball-reference
	stats_page = requests.get('https://www.basketball-reference.com/leagues/NBA_2024.html')
	content = stats_page.content
	soup = BeautifulSoup(content, 'html.parser')

	western_conf = soup.find(name='table', attrs={'id': 'confs_standings_W'})
	eastern_conf = soup.find(name='table', attrs={'id': 'confs_standings_E'})

	western_str = str(western_conf)
	eastern_str = str(eastern_conf)

	western_conf_df = pd.read_html(io.StringIO(western_str))[0]
	eastern_conf_df = pd.read_html(io.StringIO(eastern_str))[0]

	western_conf_df = western_conf_df.rename(columns={"Western Conference": "Team"})
	eastern_conf_df = eastern_conf_df.rename(columns={"Eastern Conference": "Team"})

	#Add necessary columns to standings
	standings_df = pd.concat([eastern_conf_df, western_conf_df])

	standings_df['Team'] = standings_df['Team'].astype(str)
	standings_df['Team'] = standings_df['Team'].str.replace("\([0-9]+\)", "", regex=True)
	standings_df['Team'] = standings_df['Team'].str.replace("\*", "", regex=True)
	standings_df['Team'] = standings_df['Team'].str.strip()

	standings_df['W'] = standings_df['W'].replace(np.nan, 0)
	standings_df['L'] = standings_df['L'].replace(np.nan, 0)
	standings_df['W'] = standings_df["W"].round().astype(int)
	standings_df['L'] = standings_df["L"].round().astype(int)
	standings_df["Record"] = standings_df['W'].map(str) + "-" + standings_df['L'].map(str)

	# Set up the teams
	teams = pd.DataFrame({'Team Name': ['Team Nebeyu', 
										'Team Phil', 
	                                    'Team Fitz', 
	                                    'Team Cepehr',
	                                    'Team Gabe',
	                                    'Team Young',
	                                    'Team Ben'],
	                      'Team 1': ['Golden State Warriors', 'Cleveland Cavaliers',
								   		'Boston Celtics', 'Phoenix Suns',
										'Milwaukee Bucks', 'Philadelphia 76ers', 'Denver Nuggets'],
	                      'Team 2': ['Los Angeles Lakers', 'Los Angeles Clippers',
                                     'New York Knicks', 'Oklahoma City Thunder',
									 'Minnesota Timberwolves', 'Memphis Grizzlies', 'Sacramento Kings'],
	                      'Team 3': ['Brooklyn Nets', 'Chicago Bulls',
								  		 'New Orleans Pelicans', 'Indiana Pacers',
										 'Atlanta Hawks', 'Miami Heat', 'Dallas Mavericks'],
	                      'Team 4': ['Toronto Raptors', 'Orlando Magic',
								  		 'Charlotte Hornets', 'Utah Jazz',
										 'San Antonio Spurs', 'Houston Rockets', 'Portland Trail Blazers']})

	#Create the wins table
cols_to_use = ['W', 'L', 'Record', 'Team']

merged_wins = teams.merge(standings_df[cols_to_use], left_on='Team 1', right_on='Team')
merged_wins = merged_wins.rename(columns={"W": 'Team 1 Wins', 'L': 'Team 1 Losses', "Record": "Team 1 Record"})

columns_to_drop = ['Team']
# Drop these columns
merged_wins = merged_wins.drop(columns=columns_to_drop)
merged_wins

# merged_wins = merged_wins.merge(standings_df[cols_to_use], left_on='Team 2', right_on='Team')
# merged_wins = merged_wins.rename(columns={"W": 'Team 2 Wins', 'L': 'Team 2 Losses', "Record": "Team 2 Record"})
# # Drop these columns
# merged_wins = merged_wins.drop(columns=columns_to_drop)

# merged_wins = merged_wins.merge(standings_df[cols_to_use], left_on='Team 3', right_on='Team')
# merged_wins = merged_wins.rename(columns={"W": 'Team 3 Wins', 'L': 'Team 3 Losses', "Record": "Team 3 Record"})
# # Drop these columns
# merged_wins = merged_wins.drop(columns=columns_to_drop)

# merged_wins = merged_wins.merge(standings_df[cols_to_use], left_on='Team 4', right_on='Team')
# merged_wins = merged_wins.rename(columns={"W": 'Team 4 Wins', 'L': 'Team 4 Losses', "Record": "Team 4 Record"})
# # Drop these columns
# merged_wins = merged_wins.drop(columns=columns_to_drop)

# merged_wins

,Team Name,Team 1,Team 2,Team 3,Team 4,Team 1 Wins,Team 1 Losses,Team 1 Record,Team
0,Team Nebeyu,Golden State Warriors,Los Angeles Lakers,Brooklyn Nets,Toronto Raptors,0,0,0-0,Golden State Warriors
1,Team Phil,Cleveland Cavaliers,Los Angeles Clippers,Chicago Bulls,Orlando Magic,0,0,0-0,Cleveland Cavaliers
2,Team Fitz,Boston Celtics,New York Knicks,New Orleans Pelicans,Charlotte Hornets,0,0,0-0,Boston Celtics
3,Team Cepehr,Phoenix Suns,Oklahoma City Thunder,Indiana Pacers,Utah Jazz,0,0,0-0,Phoenix Suns
4,Team Gabe,Milwaukee Bucks,Minnesota Timberwolves,Atlanta Hawks,San Antonio Spurs,0,0,0-0,Milwaukee Bucks
5,Team Young,Philadelphia 76ers,Memphis Grizzlies,Miami Heat,Houston Rockets,0,0,0-0,Philadelphia 76ers
6,Team Ben,Denver Nuggets,Sacramento Kings,Dallas Mavericks,Portland Trail Blazers,0,0,0-0,Denver Nuggets

In [17]:
merged_wins

,Team Name,Team 1,Team 2,Team 3,Team 4,Team_x,Team 1 Wins,Team 1 Losses,W/L%_x,GB_x,...,Team 2 Record,Team,Team 3 Wins,Team 3 Losses,W/L%,GB,PS/G,PA/G,SRS,Team 3 Record
0,Team Nebeyu,Golden State Warriors,Los Angeles Lakers,Brooklyn Nets,Toronto Raptors,Golden State Warriors,0,0,NaN,—,...,0-0,Brooklyn Nets,0,0,NaN,—,NaN,NaN,NaN,0-0
1,Team Phil,Cleveland Cavaliers,Los Angeles Clippers,Chicago Bulls,Orlando Magic,Cleveland Cavaliers,0,0,NaN,—,...,0-0,Chicago Bulls,0,0,NaN,—,NaN,NaN,NaN,0-0
2,Team Fitz,Boston Celtics,New York Knicks,New Orleans Pelicans,Charlotte Hornets,Boston Celtics,0,0,NaN,—,...,0-0,New Orleans Pelicans,0,0,NaN,—,NaN,NaN,NaN,0-0
3,Team Cepehr,Phoenix Suns,Oklahoma City Thunder,Indiana Pacers,Utah Jazz,Phoenix Suns,0,0,NaN,—,...,0-0,Indiana Pacers,0,0,NaN,—,NaN,NaN,NaN,0-0
4,Team Gabe,Milwaukee Bucks,Minnesota Timberwolves,Atlanta Hawks,San Antonio Spurs,Milwaukee Bucks,0,0,NaN,—,...,0-0,Atlanta Hawks,0,0,NaN,—,NaN,NaN,NaN,0-0
5,Team Young,Philadelphia 76ers,Memphis Grizzlies,Miami Heat,Houston Rockets,Philadelphia 76ers,0,0,NaN,—,...,0-0,Miami Heat,0,0,NaN,—,NaN,NaN,NaN,0-0
6,Team Ben,Denver Nuggets,Sacramento Kings,Dallas Mavericks,Portland Trail Blazers,Denver Nuggets,0,0,NaN,—,...,0-0,Dallas Mavericks,0,0,NaN,—,NaN,NaN,NaN,0-0